name: Dev Deployment

on:
  workflow_run:
    workflows: ["Build and Upload"]
    types:
      - completed

jobs:   
  deploy_to_dev:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    environment:
      name: "dev"
      url: ${{ vars.URL }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: docker-image
        path: .
    
    - name: Copy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "nextjs-dev.tar.gz"
        target: "/tmp/nextjs"

    - name: Deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /tmp/nextjs
          gunzip nextjs-dev.tar.gz
          docker load < nextjs-dev.tar
          rm -f nextjs-dev.tar
          cd /home/${{ secrets.USERNAME }}/hng_boilerplate_nextjs
          chmod +x ./scripts/*.sh
          ./scripts/dev_deploy.sh
